// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynakshhwebysychzygzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYWtzaGh3ZWJ5c3ljaHp5Z3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDk2NTEsImV4cCI6MjA2Mjc4NTY1MX0.QZDphHDBafhgRO_HBffsC2oF6OsTxEQFJ-8FBe8OO6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);